services:
  moria:
    image: andrewsav/moria
    container_name: moria
    restart: unless-stopped
    stop_signal: SIGINT
    environment:
      steamuser: anonymous
      inviteseed:
    volumes:
      - './server:/server'
      - './steam:/root/Steam'
    ports:
      - '7777:7777/udp'
